### PR TITLE
Add initial security doc with secrets maintenance info.

### LINKED ISSUE #57: check repo for secrets in git history
### Overview
We need to remove any secrets from the code base so that we can make the repo public again.

### Action Items
- [ ] Find app to search for secrets in repo, document below
- [x] Check history to find any secrets and document them below
- [x] Define any secrets we need to update.

### Resources/Instructions
- [Search string to look for apps](https://www.google.com/search?q=search+github+repo+for+secrets&oq=search+github+repo+for+secrets&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yCggCEAAYhgMYigUyCggDEAAYhgMYigUyCggEEAAYhgMYigUyCggFEAAYhgMYigXSAQkxNDc3MmowajeoAgCwAgA&sourceid=chrome&ie=UTF-8)
- [gitleaks](https://github.com/gitleaks/gitleaks)

### PR DESCRIPTION
**Pull request by Reltre**
Fixes #57 

### Context

This PR adds a new `security.md` page to the dev-docs within the tables repo. Any suggestions for copy updates here are of course welcome. We could also add this to our wiki, but I wasn't sure if we wanted this information to be in the public repo for tables or not.

### CODE REVIEW

**Review by ExperimentsInHonesty — CHANGES_REQUESTED** [review]
File is empty, please fix

**Review by Reltre — COMMENTED** [review]
This should be fixed now

**Comment by Reltre** [comment]
@wesley115 I've added a small bit of text to describe the tool and calls made to use it. Let me know if you have any suggested updates.

**Comment by wesley115** [comment]
The initial docs looks good to me, I was able to follow the instructions and did a gitleaks check on my clone repo.

For updates suggestions, upon reading the gitleaks's doc, I see it also show how to set up Pre-Commit GitLeaks checks in the repo, I wondering if we should set this up for this project

**Review by wesley115 — APPROVED** [review]
lgtm! I was able to follow the instructions and did a gitleaks check on my clone repo.

For updates suggestions, upon reading the gitleaks's doc, I see it also show how to set up Pre-Commit GitLeaks checks in the repo, I wondering if we should set this up for this project

**Comment by Reltre** [comment]
@wesley115 I think it's a good idea, but let's tackle it in another issue.

**Pull request merged**
